"""initial tables

Revision ID: 3b9367482d8c
Revises: 
Create Date: 2025-05-22 18:01:13.088610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9367482d8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bingwaoffers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bingwaoffers_id'), 'bingwaoffers', ['id'], unique=False)
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_request_id', sa.String(), nullable=False),
    sa.Column('checkout_request_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mpesa_receipt_number', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=False),
    sa.Column('result_desc', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesa_transactions_checkout_request_id'), 'mpesa_transactions', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_created_at'), 'mpesa_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_id'), 'mpesa_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_merchant_request_id'), 'mpesa_transactions', ['merchant_request_id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_mpesa_receipt_number'), 'mpesa_transactions', ['mpesa_receipt_number'], unique=True)
    op.create_index(op.f('ix_mpesa_transactions_phone_number'), 'mpesa_transactions', ['phone_number'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_result_code'), 'mpesa_transactions', ['result_code'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_status'), 'mpesa_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_updated_at'), 'mpesa_transactions', ['updated_at'], unique=False)
    op.create_table('securitycodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_securitycodes_id'), 'securitycodes', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('super_user', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('phone_number', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_securitycodes_id'), table_name='securitycodes')
    op.drop_table('securitycodes')
    op.drop_index(op.f('ix_mpesa_transactions_updated_at'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_status'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_result_code'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_phone_number'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_mpesa_receipt_number'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_merchant_request_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_created_at'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_checkout_request_id'), table_name='mpesa_transactions')
    op.drop_table('mpesa_transactions')
    op.drop_index(op.f('ix_bingwaoffers_id'), table_name='bingwaoffers')
    op.drop_table('bingwaoffers')
    # ### end Alembic commands ###
