name: Build and Copy Frontend

# Controls when the workflow will run
on:
  push:
    branches:
      - main # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js (for frontend build)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21" # Specify the version of Node.js you're using

      - name: Clean old dist folder
        run: rm -rf frontEnd/dist

      # Install dependencies and build frontend
      - name: Install dependencies and build frontend
        run: |
          cd frontEnd
          ls -la
          npm install
          npm run build
          ls dist
