name: Build and Copy Frontend

# Controls when the workflow will run
on:
  push:
    branches:
      - main # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js (for frontend build)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21" # Specify the version of Node.js you're using

      # Install dependencies and build frontend
      - name: Install dependencies and build frontend
        run: |
          cd frontEnd
          ls 
          npm install
          npm run build
          ls


    # (Optional) If you have a FastAPI deployment step, you can add it here
    # - name: Deploy to server (for example)
    #   run: <your-deployment-commands>
